routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/email', 'HomeController@email')->name('sendEmail');
Route::get('/contact/{character}', 'UserController@contact')->name('contact');
Route::get('/getad', 'UserController@getad')->name('getad');
Route::put('/sendtest', 'BulletinController@sendtest')->name('sendtest');
Route::put('/sendapproval', 'BulletinController@sendapproval')->name('sendapproval');
Route::put('/sendpublish', 'BulletinController@sendpublish')->name('sendpublish');
Route::put('/bulletinyes', 'BulletinController@bulletinyes')->name('bulletinyes');
Route::put('/bulletinno', 'BulletinController@bulletinno')->name('bulletinno');
Route::get('/printpdf/{id}', 'BulletinController@printpdf')->name('printpdf');
Route::get('/change_approvation/{id}', 'UserController@change_approvation')->name('change_approvation');
Route::put('/sendbulletin', 'BulletinController@sendbulletin')->name('sendbulletin');
Route::get('/removefile/{id}', 'BulletinController@removefile')->name('removefile');
Route::get('/requestbulletin', 'BulletinController@requestbulletin')->name('requestbulletin');
Route::get('/changepassword', 'UserController@changePassword')->name('changepassword');
Route::put('/postreset', 'UserController@postReset')->name('postreset');
Route::get('/acceptall/{id}', 'BulletinController@acceptall')->name('acceptall');
Route::get('/view/{id}', 'BulletinController@view')->name('view');
Route::get('/resend/{id}', 'BulletinController@resend')->name('resend');

Route::resource('/group', 'GroupController');
Route::resource('/bulletin', 'BulletinController');
Route::resource('/user', 'UserController');
Route::resource('/role', 'RoleController');
Route::resource('/file', 'FileController');

Route::post('/filepost', 'FileController@store')->name('filepost');

Route::get('/test/{id}', 'BulletinController@test')->name('test');
Route::post('/test_store', 'BulletinController@test_store')->name('test_store');

Route::get('/clear-cache', function () {
    $exitCode = Artisan::call('cache:clear');
    // return what you want
});

resources/views/create-bulletin.blade.php
@extends('layouts.app')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-9">
        <h2>Novo Comunicado</h2>
        <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('home') }}">Home</a>
        </li>
        <li class="breadcrumb-item">
            <a href="{{ route('bulletin.index') }}">Comunicados</a>
        </li>
        <li class="breadcrumb-item active">
            <strong>Novo Comunicado</strong>
        </li>
        </ol>
    </div>
    </div>
        @if( isset($errors) && count($errors) > 0 )
            <div class="alert alert-danger">
                @foreach( $errors->all() as $error )
                    <p>{{$error}}</p>
                @endforeach
            </div>
        @endif

        <div class="wrapper wrapper-content animated">
               <div class="row">
                   <div class="col-md-12">
                   <div class="ibox ">
                        <div class="ibox-content">
                               {!! Form::open(['route' => 'bulletin.store', 'class' => 'form', 'id' => 'form', 'method' => 'POST', 'enctype' => 'multipart/form-data']) !!}
                                   <div class="form-group row">
                                        <label class="col-lg-2 col-form-label">Assunto</label>
                                        <div class="col-lg-10">
                                                {!! Form::text('subject', null, ['class' => 'form-control', 'placeholder' => 'Assunto', 'required']) !!}
                                        </div>
                                   </div>
                                   <div class="row">
                                        <div class="col-lg-12">
                                            <div class="ibox ">
                                                <div class="ibox-content no-padding">
                                                    {!! Form::textarea('message', null, ['name' => 'message', 'class' => 'summernote', 'required']) !!}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-lg-2 col-form-label">Público Alvo</label>
                                        <div class="col-lg-4">
                                            {!! Form::select('groups[]', $groups, null, ['class' => 'form-control', 'multiple' => 'multiple', 'id' => 'groups_id', 'required']) !!}
                                        </div>
                                        <label class="col-lg-1 col-form-label">Usuários</label>
                                        <div class="col-lg-5">
                                            {!! Form::select('users[]', $users, null, ['class' => 'form-control', 'multiple' => 'multiple', 'id' => 'users_id']) !!}
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-lg-2 col-form-label">Data da publicação</label>
                                        <div class="col-lg-4">
                                            {!! Form::text('date_post', null, ['class' => 'form-control', 'id' => 'datepicker', 'required']) !!}
                                        </div>
                                        <label class="col-lg-1 col-form-label">Prioridade</label>
                                        <div class="col-lg-5">
                                            {!! Form::select('priorities[]', array('1' => 'Alta', '2' => 'Média', '3' => 'Baixa'), null, ['class' => 'form-control select2', 'id' => 'groups']) !!}
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-lg-2 col-form-label">Incluir Arquivo</label>
                                        <div class="col-lg-10">
                                            <div class="needsclick dropzone" id="document-dropzone" style="border: dashed 1px gray; background-color: white;">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <div class="col-lg-offset-2 col-lg-10">
                                            <button class="btn btn-success btn-lg" type="submit"><i class="fa fa-arrow-circle-up"></i>&nbsp;&nbsp;Enviar Solicitação</button>
                                            <!--<button class="btn btn-secondary btn-lg" type="submit">Salvar Sem Enviar</button>
                                            <button class="btn btn-success btn-lg " type="submit" formaction="/sendbulletin">Enviar Solicitação</button>-->
                                        </div>
                                    </div>
                                {!! Form::close() !!}
                           </div>
                   </div>
               </div>
   		</div>
 @endsection

resources/views/groups.blade.php
@extends('layouts.app')

@section('content')
    <div class="modal fade" id="modalCreateGroup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header text-center">
                <h4 class="modal-title w-100 font-weight-bold">Grupos</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {!! Form::open(['route' => 'group.store', 'class' => 'form']) !!}
            <div class="modal-body mx-3">
                <div class="md-form mb-5">
                    <i class="fas fa-users prefix grey-text"></i>
                    <label data-error="wrong" data-success="right" for="defaultForm-email">Nome do Grupo</label>
                    {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => '']) !!}
                </div>

                <div class="md-form mb-4">
                    <i class="fas fa-user prefix grey-text"></i>
                    <label data-error="wrong" data-success="right" for="defaultForm-pass">Contatos</label>
                    {!! Form::select('contacts[]', $contacts, null, ['class' => 'form-control select2-multi', 'multiple' => 'multiple', 'id' => 'contacts']) !!}
                </div>

            </div>
                <div class="modal-footer d-flex justify-content-center">
                    {!! Form::submit('Cadastrar', ['class' => 'btn btn-primary']) !!}
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-9">
            <h2>Grupos</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ route('group.index') }}">Home</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Grupos</strong>
                </li>
            </ol>
        </div>
    </div>
    @if( isset($errors) && count($errors) > 0 )
        <div class="alert alert-danger">
            @foreach( $errors->all() as $error )
            <p>{{ $error }}</p>
            @endforeach
        </div>
    @endif
    @if (Session::has('message'))
        <div class="alert alert-success">
            {{Session::get('message')}}
        </div>
    @endif
    <br>
    <div class='buttons' style="width:100%; overflow: auto; white-space: nowrap; margin:0px auto; padding-left:10px">
        <div style='float: left;'>
            <a href="{{ route('group.create') }}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true" float="right"><i class="fa fa-plus"></i>&nbsp;Novo</a>
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-md-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#" class="dropdown-item">Config option 1</a>
                                </li>
                                <li><a href="#" class="dropdown-item">Config option 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                    <table class="table">
                        <thead>
                            <tr>
                                <td>@sortablelink('id', '#')</td>            
                                <td>@sortablelink('name', 'Nome')</td>
                                <td>Usuários</td>
                                <td></td>
                            </tr>
                            @foreach($groups as $group)
                            <tr>
                                <td>{{$group->id}}</td>
                                <td>{{$group->name}}</td>
                                <td>
                                    @foreach ($group->users as $user)
                                        {{ $user->name }}, 
                                    @endforeach
                                </td>
                                <td>
                                <a href="{{ route('group.edit', $group->id) }}" class="btn btn-primary btn-sm" role="button"><i class="fa fa-edit"></i>&nbsp;Editar</a>
                                </td>
                            </tr>
                            @endforeach
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/request-bulletin.blade.php
@extends('layouts.app')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-9">
            <h2>Meus Comunicados</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ url('home') }}">Home</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Meus Comunicados</strong>
                </li>
            </ol>
        </div>
    </div>
    @if( isset($errors) && count($errors) > 0 )
        <div class="alert alert-danger">
            @foreach( $errors->all() as $error )
            <p>{{ $error }}</p>
            @endforeach
        </div>
    @endif
    @if (Session::has('message'))
        <div class="alert alert-success">
            {{Session::get('message')}}
        </div>
    @endif
    <br>
    @can ('create_bulletin')
        <div class='buttons' style="width:100%; overflow: auto; white-space: nowrap; margin:0px auto; padding-left:10px">
            <div style='float: left;'>
                <a href="{{ route('bulletin.create') }}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true" float="right"><i class="fa fa-plus"></i>&nbsp;Novo</a>
            </div>
        </div>
    @endcan
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-md-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <!--
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#" class="dropdown-item">Config option 1</a>
                            </li>
                            <li><a href="#" class="dropdown-item">Config option 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                        -->
                    </div>
                </div>
                <div class="ibox-content">

                    <table class="table">
                        <thead>
                        <tr>
                            <th style="width: 5%;">@sortablelink('id', '#')</th>
                            <th style="width: 10%;">@sortablelink('date_post', 'Data')</th>
                            <th style="width: 25%;">@sortablelink('subject', 'Assunto')</th>
                            <th style="width: 10%;">@sortablelink('priority', 'Prioridade')</th>
                            <th style="width: 10%;">@sortablelink('status', 'Status')</th>
                            <th style="width: 20%;">@sortablelink('created_at', 'Data Solicitação')</th>
                            <th style="width: 20%;"></th>
                        </tr>
                        </thead>
                        <tbody>
                            @can('edit_bulletin')
                                @foreach($bulletins as $bullet)
                                    @switch($bullet->status)
                                        @case(0)
                                            <tr >
                                            @break
                                        @case(1)
                                            <tr style="background: #FFFCE3;">
                                        @break
                                        @case(2)
                                            <tr style="background: #FFEBE0;">
                                        @break
                                        @case(3)
                                            <tr style="background: #FFACAB; color:white;">
                                        @break
                                        @case(4)
                                            <tr style="background: #C8EBE1;">
                                        @break
                                        @case(5)
                                            <tr style="background: #CDE2F7;">
                                        @break
                                        @case(6)
                                            <tr style="background: #DADFE6;">
                                        @break
                                    @endswitch
                                    
                                        <td style="vertical-align: middle;">{{$bullet->id}}</td>
                                        <td style="vertical-align: middle;">{{ date('d-m-Y', strtotime($bullet->date_post)) }}</td>
                                        <td style="vertical-align: middle;">{{$bullet->subject}}</td>
                                        @switch($bullet->priority)
                                            @case(1)
                                                <td style="vertical-align: middle;">Alta</td>
                                                @break
                                            @case(2)
                                                <td style="vertical-align: middle;">Média</td>
                                                @break
                                            @case(3)
                                                <td style="vertical-align: middle;">Baixa</td>
                                                @break
                                        @endswitch                                        
                                        @switch($bullet->status)
                                            @case(0)
                                                <td style="vertical-align: middle;">Enviado</td>
                                                @break
                                            @case(1)
                                                <td style="vertical-align: middle;">Em edição</td>
                                                @break
                                            @case(2)
                                                <td style="vertical-align: middle;">Aguardando aprovação</td>
                                                @break
                                            @case(3)
                                                <td style="vertical-align: middle;">Rejeitado</td>
                                                @break
                                            @case(4)
                                                <td style="vertical-align: middle;">Aprovado</td>
                                                @break
                                            @case(5)
                                                <td style="vertical-align: middle;">Publicado</td>
                                                @break
                                            @case(6)
                                                <td style="vertical-align: middle;">Cancelado</td>
                                                @break
                                        @endswitch
                                        <td style="vertical-align: middle;">{{ date('d-m-Y h:i:s', strtotime($bullet->created_at)) }}</td>
                                        <td style="vertical-align: middle;">
                                            <a href="{{ route('view', $bullet->id) }}" class="btn btn-success btn-sm" role="button"><i class="fa fa-eye"></i>&nbsp;Exibir</a>                                            
                                            @if ( $bullet->status < 4 )
                                                <a href="{{ route('bulletin.edit', $bullet->id) }}" class="btn btn-primary btn-sm" role="button"><i class="fa fa-edit"></i>&nbsp;Editar</a>
                                            @else
                                                <a href="{{ route('bulletin.edit', $bullet->id) }}" class="btn btn-secondary btn-sm" role="button"><i class="fa fa-info-circle"></i>&nbsp;Detalhes</a>
                                            @endif
                                        </td>
                                    </tr>
                                @endforeach
                            @else
                                @canany(['create_bulletin', 'approve_bulletin'])
                                    @foreach($my_bulletins as $bullet)
                                        <tr>
                                            <td>{{$bullet->id}}</td>
                                            <td>{{ date('d-m-Y', strtotime($bullet->date_post)) }}</td>
                                            <td>{{$bullet->subject}}</td>
                                            @switch($bullet->priority)
                                                @case(1)
                                                    <td>Alta</td>
                                                    @break
                                                @case(2)
                                                    <td>Média</td>
                                                    @break
                                                @case(3)
                                                    <td>Baixa</td>
                                                    @break
                                            @endswitch                                        
                                            @switch($bullet->status)
                                                @case(0)
                                                    <td>Enviado</td>
                                                    @break
                                                @case(1)
                                                    <td>Em edição</td>
                                                    @break
                                                @case(2)
                                                    <td>Aguardando aprovação</td>
                                                    @break
                                                @case(3)
                                                    <td>Rejeitado</td>
                                                    @break
                                                @case(4)
                                                    <td>Aprovado</td>
                                                    @break
                                                @case(5)
                                                    <td>Publicado</td>
                                                    @break
                                                @case(6)
                                                    <td>Cancelado</td>
                                                    @break
                                            @endswitch
                                            <td>{{ date('d-m-Y h:i:s', strtotime($bullet->created_at)) }}</td>
                                            <td>
                                                <a href="{{ route('bulletin.show', $bullet->id) }}" class="btn btn-primary btn-sm" role="button"><i class="fa fa-eye"></i>&nbsp;Exibir</a>
                                            </td>
                                        </tr>
                                    @endforeach
                                @endcan
                            @endcan
                        </tbody>
                    </table>
                    @can('edit_bulletin')
                        {{ $bulletins->links() }}
                    @else
                        @canany(['create_bulletin', 'approve_bulletin'])
                            {{ $my_bulletins->links() }}
                        @endcan
                    @endcan
                </div>
            </div>
        </div>
    </div>
 @endsection

resources/views/users.blade.php
@extends('layouts.app')

@section('content')
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-9">
            <h2>Usuários</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ route('home') }}">Home</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Usuários</strong>
                </li>
            </ol>
        </div>
    </div>
    @if( isset($errors) && count($errors) > 0 )
        <div class="alert alert-danger">
            @foreach( $errors->all() as $error )
            <p>{{ $error }}</p>
            @endforeach
        </div>
    @endif
    @if (Session::has('message'))
        <div class="alert alert-success">
            {{Session::get('message')}}
        </div>
    @endif
    <br>
    <div class='buttons' style="width:100%; overflow: auto; white-space: nowrap; margin:0px auto; padding-left:10px">
        <div style='float: left;'>
            <a href="{{ route('user.create') }}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true" float="right"><i class="fa fa-plus"></i>&nbsp;Novo</a>
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-md-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <table class="table">
                            <thead>
                                <tr>
                                    <td style="width: 5%;">@sortablelink('id', '#')</td>            
                                    <td style="width: 10%;">@sortablelink('name', 'Nome')</td>
                                    <td style="width: 20%;">@sortablelink('email', 'E-mail')</td>
                                    <td style="width: 20%;">@sortablelink('description', 'Departamento')</td>
                                    <td style="width: 25%;">@sortablelink('created_at', 'Criação')</td>
                                    <td style="width: 10%;">Grupos</td>
                                    <td style="width: 5%;">Perfis de Acesso</td>
                                    <td style="width: 5%;"></td>
                                </tr>
                            </thead>
                            <tbody style="font-size:12px;">
                                @foreach($users as $user)
                                <tr>
                                    <td style="width: 5%;">{{$user->id}}</td>
                                    <td style="width: 10%;">{{$user->name}}</td>
                                    <td style="width: 20%;">{{$user->email}}</td>
                                    <td style="width: 20%;">{{$user->description}}</td>
                                    <td style="width: 20%;">{{$user->created_at}}</td>
                                    <td style="width: 15%;">
                                        <ul>
                                        @foreach ($user->groups as $group)
                                            <a href="{{ route('group.edit', $group->id) }}" class="btn btn-outline-secondary btn-xs" role="button">{{ $group->name }}</a>
                                        @endforeach
                                        </ul>
                                    </td>
                                    <td style="width: 15%">
                                        <ul>
                                        @foreach ($user->roles as $role)
                                            <a href="{{ route('role.edit', $role->id) }}" class="btn btn-outline-secondary btn-xs" role="button">{{ $role->name }}</a>
                                        @endforeach
                                        </ul>
                                    </td>
                                    <td style="width: 5%">
                                        <a href="{{ route('user.edit', $user->id) }}" class="btn btn-secondary btn-xs" role="button">Detalhes</a>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        {!! $users->appends(\Request::except('page'))->render() !!}
                        <!--{{ $users->links() }}-->
                    </div>
                </div>
            </div>
        </div>
 @endsection